name: Discordbot
author: [JohnyMuffin, Ashleyz]
version: 1.5
main: com.johnymuffin.discordGameBridge.DiscordBot
depend:
  - DiscordCore
softdepend:
  - PermissionsEx
  - Essentials
commands:
  DiscordBridge:
    description: "Command for DiscordBridge"
